:spring_version: current
:project_id: gs-graphql-server-serialization-performance
:icons: font
:source-highlighter: prettify

https://spring.io/projects/gs-graphql-server-serialization-performancel[Spring for GraphQL Serialization Performance] is a fork of gs-graphql-server that shows the performance of GQL serialization.

== What You Will Build
You will build a service that will accept GraphQL requests at `http://localhost:8080/graphql`.

== How to use it
**Build and start the application with Gradle**

cd complete +
./gradlew bootRun

Ensure that no other process is using port 8080.
Ensure that the server started up successfully.

**Run the performance measuring script**

cd performance-measuring-script +
./measure_all.sh

== Context
We found out that GQL queries with large payloads/results are relatively slow to serialize compared with the performance required by our service and repository layer including RDBMS performance.
We wanted to measure the performance of GQL serialization and compare it with other serialization methods.

Our approach was to compare the performance of the default GQL serialization with a custom serialization method.

This is how we compared serialization performance in detail:

- The "GQL serialization"-approach is the standard way of serializing data with GQL as provided in the original gs-graphql-server sample.
We extended the original sample with a new query "allBooks" that returns a specified number of books.

`query { allBooks(nrOfBooks: $nrOfBooks) { id name pageCount author { id firstName lastName } } }`

- The "JSON via GQL serialization"-approach uses a custom query "allBooksAsJson" that returns the specified number of books and all the attributes of the "GQL serialization" query as JSON string.
We used jackson standard serialization to serialize the data to JSON.

`query { allBooksAsJSON(nrOfBooks: $nrOfBooks) }`


== Measurement

Measurement: Number of Books / Total Request Duration

|===
|Number of Books |Request Duration w/ "GQL serialization" |Request Duration w/ "JSON via GQL serialization"|Comparison Factor
|100
|9 ms
|6 ms
|1.5

|1000
|65 ms
|8 ms
|8.1

|10000
|407 ms
|26 ms
|15.7

|100000
|3961 ms
|229 ms
|17.3

|500000
|19864 ms
|1199 ms
|16.6
|===

== Conclusion

In our measurement the total request time was *was about 15 times slower using GQL serialization compared with our custom serialization method* with a high number (10 thousand or more) of books.

In our real world application the time to serialize the data is a significant part of the total request duration when retrieving a large amount of data (regardless whether pagination is user or not).

- When using Java/JPA in an AWS environment to fetch data from an AWS Postgres RDS instance we are able to fetch about 200 rows per ms (same number of fields/columns as in this example).
- When fetching 100000 books the time to fetch the data from the database is about 500 ms compared to about 4000 ms to serialize the data via GQL standard serialization which results into 11% fetching vs. 89% serialization.

We are aware that this behavior usually does not affect ordinary GQL frontends that fetch data from a GQL backend.
On the other hand this behavior can become a critical issue for use cases like data export, reporting or data transfer where a large amount of data is fetched from a GQL backend and processed further.

So *the question we are currently concerned with is whether GraphQL and GraphQL-Java is the right framework to create backends for the second category of use cases.*
